#!zsh
while true
do
  nano 01.py
  python 01.py &
  py=$!
  (sleep 5 && kill $py && echo "Killed (5 seconds)")&
  sl=$!
  wait $py
  ex=$?
  if [[ $ex != 143 ]]; then kill $sl; fi
  read n
  if [[ "$n" == "x" ]]
  then
    break
  fi
done
head -n 1 ~/.nerd/pyadventdir/01.py > 02.py
tail -n +2 01.py >> 02.py
while true
do
  nano 02.py
  python 02.py &
  py=$!
  (sleep 5 && kill $py && echo "Killed (5 seconds)")&
  sl=$!
  wait $py
  ex=$?
  if [[ $ex != 143 ]]; then kill $sl; fi
  read n
  if [[ "$n" == "x" ]]
  then
    break
  fi
done
